server:
  port: 8081
spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
      uri: mongodb+srv://admin:admin@cluster0-slfkf.mongodb.net/test?retryWrites=true
#      uri: mongodb://localhost:27017/blog
      grid-fs-database: images
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG